Use interpreter script instead of setting PYTHONPATH.
Fixes Windows error:
Traceback (most recent call last):
  File "bin\client1-script.py", line 326, in <module>
    + sys.argv[1:]))
  File "c:\users\administrator\documents\my web sites\ploneapp15\zeocluster\src\plone.recipe.zope2instance\src\plone\recipe\zope2instance\ctl.py", line 593, in main
    os.environ['PYTHONPATH'] = os.path.pathsep.join(sys.path)
  File "C:\Users\Administrator\Documents\My Web Sites\PloneApp15\lib\os.py", line 420, in __setitem__
    putenv(key, item)
ValueError: the environment variable is longer than 32767 bytes